services:
  compiler:
    container_name: codearcade-compiler
    image: gtinna005/codearcade-compiler:latest
    ports:
      - "3002:3002"
    env_file:
      - ./Compiler/.env
    networks:
      - app-network

  backend:
    container_name: codearcade-backend
    image: gtinna005/codearcade-backend:latest
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env
    depends_on:
      - compiler
      - redis
    networks:
      - app-network

  redis:
    container_name: codearcade-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
