name: Build and Push Docker Images (Backend & Compiler)

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # run on manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push backend image
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codearcade-backend:latest

      # Step 4: Build and push compiler image
      - name: Build and Push Compiler Image
        uses: docker/build-push-action@v2
        with:
          context: ./Compiler
          file: ./Compiler/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codearcade-compiler:latest
